import os

SECRET_KEY = os.environ.get('SECRET_KEY')

SESSION_COOKIE_SECURE = False
SESSION_COOKIE_HTTPONLY = False

CACHE_TYPE = "FileSystemCache"
DAILY_LIMIT = 1000
HOURLY_LIMIT = 240

PROCESSED_FILES_DIRECTORY = ""